# =============================================
# Application
# =============================================
quarkus.application.name=customer-service
quarkus.http.port=8081
quarkus.http.host=0.0.0.0

# =============================================
# DataSource (PostgreSQL)
# =============================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# --- Mode DEV (mvn quarkus:dev) → localhost ---
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/customerdb

# --- Mode PROD (Docker) → nom du conteneur Docker ---
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-customer:5432/customerdb

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# =============================================
# Service Discovery (via Stork + Consul)
# =============================================
# Enregistrement de CE service dans Consul via Stork
quarkus.stork.customer-service.service-registrar.type=consul

# --- Mode DEV → Consul sur localhost ---
%dev.quarkus.stork.customer-service.service-registrar.consul-host=localhost

# --- Mode PROD (Docker) → Consul via nom de conteneur ---
%prod.quarkus.stork.customer-service.service-registrar.consul-host=consul

quarkus.stork.customer-service.service-registrar.consul-port=8500

# Activer Swagger UI même en PROD (Docker)
quarkus.swagger-ui.always-include=true
