# =============================================
# Application
# =============================================
quarkus.application.name=gateway-service
quarkus.http.port=8888
quarkus.http.host=0.0.0.0

# =============================================
# Découverte du customer-service via Consul
# =============================================
quarkus.stork.customer-service.service-discovery.type=consul
%dev.quarkus.stork.customer-service.service-discovery.consul-host=localhost
%prod.quarkus.stork.customer-service.service-discovery.consul-host=consul
quarkus.stork.customer-service.service-discovery.consul-port=8500
quarkus.stork.customer-service.service-registrar.enabled=false

# =============================================
# Découverte du billing-service via Consul
# =============================================
quarkus.stork.billing-service.service-discovery.type=consul
%dev.quarkus.stork.billing-service.service-discovery.consul-host=localhost
%prod.quarkus.stork.billing-service.service-discovery.consul-host=consul
quarkus.stork.billing-service.service-discovery.consul-port=8500
quarkus.stork.billing-service.service-registrar.enabled=false

# =============================================
# REST Clients
# =============================================
quarkus.rest-client.customer-api.url=stork://customer-service
quarkus.rest-client.billing-api.url=stork://billing-service

# Enregistrement de ce service dans Consul via Stork
quarkus.stork.gateway-service.service-registrar.type=consul
%dev.quarkus.stork.gateway-service.service-registrar.consul-host=localhost
%prod.quarkus.stork.gateway-service.service-registrar.consul-host=consul
quarkus.stork.gateway-service.service-registrar.consul-port=8500

# Activer Swagger UI même en PROD (Docker)
quarkus.swagger-ui.always-include=true
