# =============================================
# Application
# =============================================
quarkus.application.name=billing-service
quarkus.http.port=8082
quarkus.http.host=0.0.0.0

# =============================================
# DataSource (PostgreSQL)
# =============================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/billingdb

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# =============================================
# Eureka Service Discovery (via Stork)
# =============================================
# 1. Enregistrement du billing-service dans Consul
quarkus.stork.billing-service.service-registrar.type=consul
quarkus.stork.billing-service.service-registrar.consul-host=localhost
quarkus.stork.billing-service.service-registrar.consul-port=8500

# 2. Découverte du customer-service via Consul
quarkus.stork.customer-service.service-discovery.type=consul
quarkus.stork.customer-service.service-discovery.consul-host=localhost
quarkus.stork.customer-service.service-discovery.consul-port=8500
quarkus.stork.customer-service.service-registrar.enabled=false

# =============================================
# REST Clients
# =============================================
quarkus.rest-client.CUSTOMER-SERVICE.url=stork://customer-service